return {
    ['Lastenola'] = true,
    ['78cvzl'] = false,
    ['YOURBADS7'] = true,
    ["darkgamer_alt354"] = true,
    ["oooohmdr2010"] = true,
    ["zazaboubou_1"] = true,
    ["17K_xVibezzzz"] = true,
    ["Lockzzscm"] = true,
    ["WhyImPlayThisGame666"] = true,
    ["CryForCyr0"] = true,
    ["Test002533533"] = true,
    ["LockZzScm"] = true,
    ["AshtvnGetBanPfff"] = true,
    ["darkgamer_ALT543"] = true,
}
